# 1 워크플로의 이름 지정
name: Django CI

# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # 3. 실행 환경 지정
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 4는 Github Actions에서 제공하는 기본 파일의 설정
      max-parallel: 4
      matrix:
        python-version: [3.11]
    # 4. 실행 스템 지정
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

#    - name: create-json
#      id: create-json
#      uses: jsdaniell/create-json@1.1.2
#      with:
#        name: "secrets.json"
#        json: ${{ secrets.SECERT_JSON }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_bk.txt

    - name: Run Tests
      run: |
        python manage.py test

    - name: excuting remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
#        host: ${{ secrets.REMOTE_SSH_HOST }}
#        port: ${{ secrets.REMOTE_SSH_PORT }}
#        username: ${{ secrets.REMOTE_SSH_USERNAME }}
#        password: ${{ secrets.REMOTE_SSH_PASSWORD }}
#        key: ${{ secrets.REMOTE_SSH_KEY }}
        host: "106.255.245.242"
        port: "22"
        username: "agics-ai"
#        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABhAC0CpofG/8sQcFrpVDV8ovofcfYq6zij3oqkvz0CCwThagB31pCTDIZ6R48TFXUN8Dp6nuI8MAq4oYd55HgoR9cZSNP29XXYZthje37lp4vp+Qq3BbvTtU74RffMbq+rHMgAhhOYdGQ5gWg9a2SsHJUwG+NPKUp1n1NQ/HZjGzkjjKgT5GrKDqUg6WCWDtkCJRDnB3ws1WEgnki/eypnCxp2GtQ0RZGxXalx2zqJVrPjNKzvswke5yWD0ervRpHkqaVbS1gZxmRn3QdplRZVLFEuAu94vL6KuqBCMFYeWMtJznyCRejTYXd1Ht851ZIvvFbJ6oWGHYUEWM98WNGVBXG4Z6vnWSvWCjsufa4JUKWq7fqnwrIXu14ZwiTgI8YicS9XAQ1NrdG36bZPZ6lHqvEr/VuMt2YYwG2OCwfECgQBOy8vqt6KIqlsXNsQQvI4xP5ljSWVmecKih8hYHg37mDZJ4T9HXAdvc9R20BLiMWlfEHCsaLKB7pT+s53ri+qE9NRg0= lms980321@kakao.com"
        password: "agics12!@"
        debug: true
#        key_path: "/home/agics-ai/.ssh/id_rsa"
        scripts: whoami
